/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppReceitasRouteImport } from './routes/_app/receitas'
import { Route as AppPrevistoRealizadoRouteImport } from './routes/_app/previsto-realizado'
import { Route as AppFluxoCaixaRouteImport } from './routes/_app/fluxo-caixa'
import { Route as AppExternoRouteImport } from './routes/_app/externo'
import { Route as AppDreRouteImport } from './routes/_app/dre'
import { Route as AppDespesasRouteImport } from './routes/_app/despesas'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppAlertasRouteImport } from './routes/_app/alertas'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrevistoRealizadoRoute = AppPrevistoRealizadoRouteImport.update({
  id: '/previsto-realizado',
  path: '/previsto-realizado',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExternoRoute = AppExternoRouteImport.update({
  id: '/externo',
  path: '/externo',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDreRoute = AppDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDespesasRoute = AppDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/alertas': typeof AppAlertasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/despesas': typeof AppDespesasRoute
  '/dre': typeof AppDreRoute
  '/externo': typeof AppExternoRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/previsto-realizado': typeof AppPrevistoRealizadoRoute
  '/receitas': typeof AppReceitasRoute
}
export interface FileRoutesByTo {
  '/alertas': typeof AppAlertasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/despesas': typeof AppDespesasRoute
  '/dre': typeof AppDreRoute
  '/externo': typeof AppExternoRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/previsto-realizado': typeof AppPrevistoRealizadoRoute
  '/receitas': typeof AppReceitasRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/despesas': typeof AppDespesasRoute
  '/_app/dre': typeof AppDreRoute
  '/_app/externo': typeof AppExternoRoute
  '/_app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/_app/previsto-realizado': typeof AppPrevistoRealizadoRoute
  '/_app/receitas': typeof AppReceitasRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/dashboard'
    | '/despesas'
    | '/dre'
    | '/externo'
    | '/fluxo-caixa'
    | '/previsto-realizado'
    | '/receitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alertas'
    | '/configuracoes'
    | '/dashboard'
    | '/despesas'
    | '/dre'
    | '/externo'
    | '/fluxo-caixa'
    | '/previsto-realizado'
    | '/receitas'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/alertas'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/despesas'
    | '/_app/dre'
    | '/_app/externo'
    | '/_app/fluxo-caixa'
    | '/_app/previsto-realizado'
    | '/_app/receitas'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/receitas': {
      id: '/_app/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/previsto-realizado': {
      id: '/_app/previsto-realizado'
      path: '/previsto-realizado'
      fullPath: '/previsto-realizado'
      preLoaderRoute: typeof AppPrevistoRealizadoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fluxo-caixa': {
      id: '/_app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/externo': {
      id: '/_app/externo'
      path: '/externo'
      fullPath: '/externo'
      preLoaderRoute: typeof AppExternoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dre': {
      id: '/_app/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AppDreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/despesas': {
      id: '/_app/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AppDespesasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDespesasRoute: typeof AppDespesasRoute
  AppDreRoute: typeof AppDreRoute
  AppExternoRoute: typeof AppExternoRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppPrevistoRealizadoRoute: typeof AppPrevistoRealizadoRoute
  AppReceitasRoute: typeof AppReceitasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDespesasRoute: AppDespesasRoute,
  AppDreRoute: AppDreRoute,
  AppExternoRoute: AppExternoRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppPrevistoRealizadoRoute: AppPrevistoRealizadoRoute,
  AppReceitasRoute: AppReceitasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
